#spring.application.name=backend
#spring.data.mongodb.uri=mongodb://localhost:27017/mynotes
#server.port=8080


#spring.data.mongodb.uri=mongodb+srv://notesapp:pavan123@cluster0.zp9d88z.mongodb.net/notesdb?retryWrites=true&w=majority&appName=Cluster0
#server.port=8080
#spring.data.mongodb.uri=${MONGODB_URI}
#server.port=${PORT:8080}


spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://notesapp:pavan123@cluster0.zp9d88z.mongodb.net/notesdb?retryWrites=true&w=majority&appName=Cluster0
server.port=${PORT:8080}
