spring.application.name=backend
server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://notesapp-user:pavan123@cluster0.zp9d88z.mongodb.net/notesapp?retryWrites=true\&w=majority\&appName=Cluster0
